import type { SaaSBuilderOutput } from "@/lib/omniagent/types";

export function formatProjectMarkdown(project: SaaSBuilderOutput) {
  const lines = [
    `# ${project.landingPage.headline}`,
    "",
    project.landingPage.subheadline,
    "",
    "## Resumen",
    "",
    `- Idea: ${project.input.idea}`,
    `- Audiencia: ${project.input.audience || "No definida"}`,
    `- Mercado: ${project.input.region || "No definido"}`,
    `- Score: ${project.nicheValidation.score}/100`,
    `- Veredicto: ${project.nicheValidation.verdict}`,
    "",
    "## Propuesta de valor",
    "",
    project.valueProposition,
    "",
    "## Validacion del nicho",
    "",
    project.nicheValidation.summary,
    "",
    ...project.nicheValidation.marketSignals.map(
      (signal) => `- **${signal.label}** (${signal.strength}): ${signal.rationale}`,
    ),
    "",
    "## Usuarios objetivo",
    "",
    ...project.targetUsers.map((user) => `- ${user}`),
    "",
    "## Features MVP",
    "",
    ...project.mvpFeatures.map(
      (feature) => `- **${feature.priority}** ${feature.name}: ${feature.outcome} (${feature.owner})`,
    ),
    "",
    "## Arquitectura tecnica",
    "",
    "### Stack",
    ...project.technicalArchitecture.stack.map((item) => `- ${item}`),
    "",
    "### Modulos",
    ...project.technicalArchitecture.modules.map((item) => `- ${item}`),
    "",
    "### Datos",
    ...project.technicalArchitecture.dataModel.map((item) => `- ${item}`),
    "",
    "### Integraciones",
    ...project.technicalArchitecture.integrations.map((item) => `- ${item}`),
    "",
    "## Backlog MVP",
    "",
    ...project.backlog.flatMap((item) => [
      `- **${item.id}** ${item.title} (${item.estimateDays}d, ${item.agent})`,
      ...item.acceptanceCriteria.map((criterion) => `  - ${criterion}`),
    ]),
    "",
    "## Landing page",
    "",
    `- Headline: ${project.landingPage.headline}`,
    `- Subheadline: ${project.landingPage.subheadline}`,
    `- CTA: ${project.landingPage.primaryCta}`,
    ...project.landingPage.sections.map((section) => `- ${section.title}: ${section.body}`),
    "",
    "## Pricing",
    "",
    ...project.pricing.flatMap((plan) => [
      `- **${plan.name}** - ${plan.price}`,
      `  - Target: ${plan.target}`,
      ...plan.includes.map((item) => `  - ${item}`),
    ]),
    "",
    "## Plan de lanzamiento de 7 dias",
    "",
    ...project.launchPlan7Days.map((step) => `- Dia ${step.day}: ${step.goal} - ${step.actions.join("; ")}`),
    "",
    "## Primeros clientes",
    "",
    ...project.firstCustomerPlan.map((step) => `- ${step}`),
    "",
    "## Riesgos",
    "",
    ...project.risks.map((risk) => `- ${risk}`),
  ];

  return `${lines.join("\n").trim()}\n`;
}
